version: '3.8'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  nethra_monitoring:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: nethra_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - nethra_monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: nethra_grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=nethra_admin
      - GF_SECURITY_ADMIN_PASSWORD=nethra123
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/nethra-dashboard.json
    ports:
      - "3000:3000"
    networks:
      - nethra_monitoring
    restart: unless-stopped
