global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nethra-fastapi-backend'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 10s
    metrics_path: '/metrics'
    
  - job_name: 'nethra-trust-scores'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 5s
    metrics_path: '/api/monitoring/trust-metrics'
